# Generated by Django 5.2 on 2025-05-07 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_timestamp_lead_phone_lead_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
