# Generated by Django 5.2 on 2025-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_timestamp_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
