# Generated by Django 5.2 on 2025-07-01 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_whatsappsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('template_type', models.CharField(choices=[('initial', 'Initial'), ('followup1', '15-min Follow-up'), ('followup2', '1-hour Follow-up')], max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
