# Generated by Django 5.2 on 2025-07-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_messagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
