# Generated by Django 5.2.4 on 2025-07-23 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_delete_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('template_type', models.CharField(choices=[('initial', 'Initial'), ('followup1', '15-min Follow-up'), ('followup2', '1-hour Follow-up'), ('status_updated', 'Status Updated')], max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
