# Generated by Django 5.2.4 on 2025-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='template_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('followup1', '15-min Follow-up'), ('followup2', '1-hour Follow-up')], max_length=20),
        ),
    ]
